name: CI

on:
  release:
    types: [created]

jobs:
  build:
    env:
      BUILD_CONFIG: Release

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Get Build Version
        run: |
          Import-Module .\build\GetBuildVersion.psm1
          Write-Host $Env:GITHUB_REF
          $version = GetBuildVersion -VersionString $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          echo "BUILD_VERSION=$version"
        shell: pwsh

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Add github packages source
        run: dotnet nuget update source github --configfile ./nuget.config -s "https://nuget.pkg.github.com/Semifinals/index.json" -u ${{ secrets.SOURCE_USER }} -p ${{ secrets.SOURCE_PASSWORD }} --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore --configfile ./nuget.config

      - name: Build
        run: dotnet build --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

      - name: Run tests
        run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal

      - name: Package the project
        run: dotnet pack --configuration $BUILD_CONFIG

      - name: Publish
        run: dotnet nuget push "Framework/bin/${{ env.BUILD_CONFIG }}/Semifinals.Framework.${{ env.BUILD_VERSION }}.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
